CI: Fix core_assertions LoadError in Windows cases
This commit fixes the following CI failures in Windows.
I don't know why this change fixed. Perhaps Bundler's handling with git
repository is different.

https://github.com/ruby/drb/actions/runs/32029577375/job/95386338154?pr=54
```
D:/a/drb/drb/test/lib/helper.rb:2:in 'Kernel#require': cannot load such file -- core_assertions (LoadError)
	from D:/a/drb/drb/test/lib/helper.rb:2:in '<top (required)>'
	from <internal:D:/rubyinstaller-head-x64/lib/ruby/4.1.0+4/rubygems/core_ext/kernel_require.rb>:139:in 'Kernel#require'
rake aborted!
Command failed with status (1)
D:/a/drb/drb/vendor/bundle/ruby/4.1.0+4/gems/rake-13.4.2/exe/rake:27:in '<top (required)>'
D:/rubyinstaller-head-x64/bin/bundle:33:in '<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```